// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkoseuT3duzJbQ_SytICj7MgefRxbGbek',
    appId: '1:93485447785:web:a2f5d937a27c6b007b80f8',
    messagingSenderId: '93485447785',
    projectId: 'demoflutter-ea7de',
    authDomain: 'demoflutter-ea7de.firebaseapp.com',
    storageBucket: 'demoflutter-ea7de.appspot.com',
    measurementId: 'G-SRBYBH6KTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBzC54MdYGl4ZfAJ3S_EnFneLUvdzGZOA',
    appId: '1:93485447785:android:d39ee6091aff82f97b80f8',
    messagingSenderId: '93485447785',
    projectId: 'demoflutter-ea7de',
    storageBucket: 'demoflutter-ea7de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHV8cs0WTG7UMYIALACbGyaSRLuKqh5Ds',
    appId: '1:93485447785:ios:b1e5b039dfade8077b80f8',
    messagingSenderId: '93485447785',
    projectId: 'demoflutter-ea7de',
    storageBucket: 'demoflutter-ea7de.appspot.com',
    iosClientId: '93485447785-88kqs2j8kl4tbtdd310jd1mnikr9lng9.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoparts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHV8cs0WTG7UMYIALACbGyaSRLuKqh5Ds',
    appId: '1:93485447785:ios:b1e5b039dfade8077b80f8',
    messagingSenderId: '93485447785',
    projectId: 'demoflutter-ea7de',
    storageBucket: 'demoflutter-ea7de.appspot.com',
    iosClientId: '93485447785-88kqs2j8kl4tbtdd310jd1mnikr9lng9.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoparts',
  );
}
